### PR TITLE
Patches for Python 3.10 

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
Fixes https://github.com/Erotemic/utool/issues/12

**Comment by Erotemic** [comment]
Hi, thanks for the patch. Unfortuantely the dashboards for this repo aren't the greatest, and I'd like to ensure that any changes to this repo continues to work with older versions of Python (e.g. 2.7), so instead of just changing to collections.abc.Mapping, could we do:

```python
try:
    from collections import Mapping
except Exception:
    from collections.abc import Mapping
```

And then use `Mapping` as the base class?

Also, this repo is in maintenance only mode, I'm curious what you are using it for / what the dependency chain that uses this library is?

See https://github.com/Erotemic/ubelt for an actively developed subset of functions in this library. If there is something in utool that is useful, but not in ubelt or another one of my actively maintained repos (e.g. xdev), let me know and I'll port it.

**Comment by jan-janssen** [comment]
I mainly maintain the `conda-forge` packages and I guess it is still required for https://github.com/Erotemic/dtool_ibeis right ?

**Comment by Erotemic** [comment]
Ultimately, it's for use in [ibeis](https://github.com/Erotemic/ibeis), which is still in use, although I would like to phase it out completely.

**Comment by Erotemic** [comment]
I fixed this in a different PR to maintain Python 2 support. The main branch should be passing.

**Pull request closed without merging**
