### PR TITLE
Add option to use futures.ThreadPoolExecutor in util_parallel.generate2()

### PR DESCRIPTION
**Pull request by bluemellophone**
Fairly simply configuration to allow future pool workers threads instead of process.  This PR adds the option to specify `use_futures_thread` (default to False to maintain existing behavior) to True to switch backend workers.  This PR is important, at the very least, for macOS and OpenCV 3.4.X which has issues with manipulating images in multiprocessing older versions of Python, ref: https://github.com/opencv/opencv/issues/5150

### CODE REVIEW

**Comment by bluemellophone** [comment]
Poke

**Comment by Erotemic** [comment]
Sorry, missed this when it was originally submitted. LGTM. 

Note, these days I'm using a slightly simpler abstraction around concurrent.futures: https://github.com/Kitware/kwcoco/blob/master/kwcoco/util/util_futures.py#L121

The `JobPool` object uses a very similar API to the regular concurrent.futures, except it maintains a list of the jobs that were submitted, and it allows switching between thread, process, and serial mode. I'd recommend using some construct like that rather than relying on utool (which I would encourage that you move away from).

**Comment by Erotemic** [comment]
@bluemellophone Do you need a new pypi release for this?

**Comment by bluemellophone** [comment]
No, a dedicated release is not necessary.  We have released this fix on PyPI as `wbia-utool` and are using that fork for all of the `wildbook-ia` (wbia) repositories.  This PR was simply back porting one of the options that we found very useful for macOS development.  You can now install the latest production version of WBIA on macOS and Linux as well as our public production Docker images `wildme/wbia:latest`

```
mkdir -p ~/virtualenv/
python3.7 -m venv ~/virtualenv/wbia3.7/
source ~/virtualenv/wbia3.7/bin/activate
pip install wildbook-ia

# Install any plugins
pip install git+https://github.com/WildbookOrg/wbia-plugin-curvrank.git@develop#egg=wbia_curvrank

python -m wbia.dev --cmd
```

or 

```
docker run wildme/wbia:latest
```

**Pull request merged**
